### ISSUE TITLE
settings.json config is not available after deploy

### ISSUE THREAD

**Issue by deleuterio** [andreafabrizi/Dropbox-Uploader#283]
Hello, 
I saw some post with same error attached: 
![selection_016](https://cloud.githubusercontent.com/assets/12951402/13683524/df5f8b54-e6e5-11e5-8410-d4f9ca5e220b.png)
Ok, I see other issues like that, example:
https://github.com/arunoda/meteor-up/issues/226

But mup logs show this error:

```BASH
/opt/se-edu/app/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'S3' of undefined
    at FS.Store.S3.Meteor.isServe[XXX.XXX.XXX.XXX] r.region (collections/documents.js:4:45)
    at /opt/se-edu/app/programs/server/packages/somefile-files.js:57:4
    at /opt/se-edu/app/programs/server/packages/somefile-files.js:166:3
    at /opt/se-edu/app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/se-edu/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/se-edu/app/programs/server/boot.js:137:5
error: Forever detected script exited with code: 8
error: Script restart attempt #67

/opt/se-edu/app/programs/server/boot.js:283
}).run();
   ^
Error: ENOENT, no such file or directory '/opt/se-edu/app/programs/server/npm/ecmascript-runtime/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.array.from.js'
    at Object.fs.lstatSync (fs.js:691:18)
    at Object.realpathSync (fs.js:1279:21)
    at tryFile (module.js:142:15)
    at tryExtensions (module.js:150:20)
    at Function.Module._findPath (module.js:185:20)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/se-edu/app/programs/server/npm/ecmascript-runtime/node_modules/meteor-ecmascript-runtime/node_modules/core-js/es6/array.js:2:1)
error: Forever detected script exited with code: 8
error: Script restart attempt #68

```
I get it the settings.json is not deployed correct and then is unnavailable on server side and client side scope.
I try run mup setup and deploy again but the problem still happens.

finally, my mup.json
```JSON
{
  "servers": [
    {
      "host": "XXX.XXX.XXX.XXX",
      "username": "ubuntu",
      "pem": "~/.ssh/somekey.pem"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.40",
  "setupPhantom": true,
  "enableUploadProgressBar": true,
  "appName": "se-edu",
  "app": ".",
  "env": {
    "ROOT_URL": "http://XXX.XXX.XXX.XXX"
  },
  "deployCheckWaitTime": 120
}
```

**Comment by deleuterio** [comment]
Sorry, wrong project.
