### ISSUE TITLE
uploading issue when run in python script

### ISSUE THREAD

**Issue by tachyon83** [andreafabrizi/Dropbox-Uploader#474]
hello there,

I am trying to upload image files (the whole things in a folder) from Raspberry Pi to my Dropbox.
If I say "/home/pi/Dropbox-Uploader/dropbox-uploader.sh upload 'my file folder' 'my Dropbox destination folder" in the Raspberry Pi terminal, it works perfectly fine.
But when I try this command in Python script, somehow it does not work.
I think it should do the same thing but I don't know why and I badly need some help.

Below is what I did:
===========================================================
from subprocess import Popen,PIPE
import time, os, subprocess
import psutil
import glob
import fnmatch
import subprocess
import shutil

os.system('/home/pi/Dropbox-Uploader/dropbox_uploader.sh upload /home/pi/images /')
============================================================

/home/pi/images is where my images are located.
I just want to upload those images to my dropbox folder. (did not specify it)
I strongly believe that this is a very trivial matter. Please help me

Thank you in advance and please let me know if you need more information

**Comment by necmettin** [comment]
if using ' characters in the command line works, did you try

`os.system("/home/pi/Dropbox-Uploader/dropbox_uploader.sh upload '/home/pi/images' '/'")`

in python?

also, did you try `/home/pi/images/*` ?

If it is working fine in the command line, this obviously is not about dropbox_uploader but about the command line you are running through Python.

**Comment by tachyon83** [comment]
I am sorry for getting back to you so late.

I actually tried a different way and got it working. I am sorry about not watching your reply.

But again I got another problem.

Here is the description:

I have two camera modules connected(wired and configured) to two raspberrypies(one for each). These cameras take pictures and save the image onto the pies. I have one Dropbox account. I have a code to upload image files (saved in the specified folder) from the pi to my Dropbox account. 

So, when I give a command, these two pies start uploading the image files to my Dropbox account at the same time. 

And the problem comes into play. Always one pi succeed in uploading. The other fails. I need help on this. And I am planning to have 20 cameras. So 20 pies should be able to upload images to one single Dropbox account at the same time.

Thank you for your help. I hope the solution is easy and straightforward. 


Code:
import dropbox, sys, os
import os.path
from dropbox.files import WriteMode

dbx=dropbox.Dropbox('my authentication key')
image_dir="/home/pi/somefolder"

for dir, dirs, files in os.walk(image_dir):
     for file in files:
          file_path=os.path.join(dir, file)
          dest_path=os.path.join('/somefolder', file)
          with open(file_path) as f:
               dbx.files_upload(f.read(), dest_path, mute=True, 
               mode=WriteMode('add'))
-------------------------------------------------------------------------------------
When I run only one pi, the uploading works perfect. No problem at all. When I run two pies uploading at the same time, always one of them malfunctions. 

here below I have attached what I get from the malfunctioning pi.
the error messages:

Traceback (most recent call last):
File "scanner.py", line 288, in dest_path, mute=True, mode=WriteMode('add'))
 File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 2293, in files_upload f,
 File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 274, in request timeout=timeout)
 File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry timeout=timeout)
 File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 449, in request_json_string timeout=timeout,
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 581, in post return self.request('POST', url, data=data, json=json, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by New ConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name r esolution',))


I really hope someone can help me with this issue. Thank you very much in advance.

**Comment by necmettin** [comment]
So if it only one RPi, it works, no matter which one. But if both runs at the same time, one always fails (I'm guessing the second one that started syncing)?

Apparently, Dropbox has some undocumented per-user limits, although they aren't giving any specific numbers: https://stackoverflow.com/questions/41105196/limits-on-dropbox-api-when-calling-from-a-single-account.

Did you try starting the second RPi sync say 5 minutes after the first, what happened then? Did you try starting one sync a few seconds after the first one finishes?

The thing is, if both RPis have the exact same dropbox keys and one works as long as the other isn't working, then I would wager this problem is not about dropbox_uploader but about Dropbox limitations.

In this scenaris, I would set up scripts to move all upload queue to one of the RPis and do all the uploading from there. A script to scp files from the other RPis, upload them, and then remove them from the filesystem should suffice.

**Comment by tachyon83** [comment]
Thank you very much for your quick response.

Yes as you guessed, one always fails. The second one.
And also as you said, maybe this could be a problem about Dropbox limitations, I am sorry about that.

Like you said, I am just uploading image files from one RPi at a time. That is just a temporary solution for now. But I will definitely consider your suggestions. Thank you very much
